import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TanstackProvider } from '@/providers/TanstackProvider';
import { Toaster } from 'sonner';
import { DynamicLayout } from '@/components/layouts/dynamic-layout';
import { cn } from '@/lib/utils';
import { QueryClient } from '@tanstack/react-query';

const fontInter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'h-screen bg-background font-sans antialiased',
          fontInter.variable
        )}
      >
        <TanstackProvider>
          <Toaster />
          <DynamicLayout navCollapsedSize={0}>{children}</DynamicLayout>
        </TanstackProvider>
      </body>
    </html>
  );
}
